### ISSUE TITLE
Use Giphy to Pull Weather Fiphy

### ISSUE THREAD

**Issue by Kay0s** [nobleburgundy/weather-jamz#20]
Instead of a music API, should we use GIPHY to pull a weather related giff?

**Comment by klyngdal** [comment]
James we pretty much came to the conclusion that there just aren't any good API's for music.. SO  we were talking about using gif api that reflects the weather, maybe background changed based on the background, or a recipes.. any other ideas? 

We thought since we have already used the gif API might be easier to go that route.. 

How does everyone else feel about it? Ideas?

**Comment by randyWhitley** [comment]
Real name idea— weathercock GIFs

**Comment by Kay0s** [comment]
Closed since last fm's API can be used.
